{
 "title": "Web Tools",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Incoming Request Rate",
   "type": "stat",
   "description": "Incoming Request Rate",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_count{job=\"web-tools\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "99th Percentile Latency",
   "type": "stat",
   "description": "99th Percentile Latency",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_latency_bucket{job=\"web-tools\"}[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_count_by_status_code{job=\"web-tools\", http_status=~\"[1234]..\"}[$__interval])) / sum(rate(http_server_response_count_by_status_code{job=\"web-tools\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Incoming Request Rate",
   "type": "graph",
   "description": "Incoming Request Rate",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_latency_by_path_count{job=\"web-tools\"}[$__interval])) by (http_server_route)",
     "legendFormat": "{{http_server_route}}"
    }
   ]
  },
  {
   "title": "Server Latency By Endpoint (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_latency_by_path_bucket{job=\"web-tools\"}[$__interval])) by (http_server_route, le)) ",
     "legendFormat": "{{http_server_route}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_response_count_by_status_code{job=\"web-tools\", http_status=~\"[45]..\"}[$__interval])) / sum(rate(http_server_response_count_by_status_code{job=\"web-tools\"}[$__interval]))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Incoming Request Latency",
   "type": "graph",
   "description": "Incoming Request Latency",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_latency_bucket{job=\"web-tools\"}[$__interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_latency_bucket{job=\"web-tools\"}[$__interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_latency_bucket{job=\"web-tools\"}[$__interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_latency_bucket{job=\"web-tools\"}[$__interval])) by (le))",
     "legendFormat": "99.9th"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(http_server_latency_bucket{job=\"web-tools\"}[$__interval])) by (le))",
     "legendFormat": "99.99th"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Network I/O",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_request_bytes_sum{job=\"web-tools\"}[$__interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(http_server_response_bytes_sum{job=\"web-tools\"}[$__interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Response Rate by Status",
   "type": "graph",
   "description": "Response Rate by Status",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_response_count_by_status_code{job=\"web-tools\"}[$__interval])) by (http_status)",
     "legendFormat": "{{ http_status }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"web-tools\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"web-tools\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Use Case Rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(use_case_interactions_count{job=\"web-tools\"}[$__interval])) by (name,status)",
     "legendFormat": "{{name}}:{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Client Latency (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_latency_by_host_bucket{job=\"web-tools\"}[$__interval])) by (http_client_host, le)) ",
     "legendFormat": "{{http_client_host}}"
    }
   ]
  },
  {
   "title": "Database Latency (99.9th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(go_sql_client_latency_bucket{job=\"web-tools\"}[$__interval])) by (go_sql_status,le)) ",
     "legendFormat": "{{go_sql_status}}"
    }
   ]
  },
  {
   "title": "Cache Miss/Write Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_miss{job=\"web-tools\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} miss"
    },
    {
     "expr": "sum(rate(cache_write{job=\"web-tools\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} write"
    },
    {
     "expr": "sum(rate(cache_expired{job=\"web-tools\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} expired"
    },
    {
     "expr": "sum(rate(cache_build{job=\"web-tools\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} build"
    }
   ]
  },
  {
   "title": "HTTP Client Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_client_latency_by_host_count{job=\"web-tools\"}[$__interval])) by (http_client_host)",
     "legendFormat": "{{http_client_host}}"
    }
   ]
  },
  {
   "title": "DB Operations Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sql_storage_queries_total{job=~\"web-tools\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_hit{job=~\"web-tools\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cache items count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cache_items{job=\"web-tools\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Database Operation Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(rate(sql_storage_queries_seconds{job=\"web-tools\"}[$__interval])) by (method) / sum(rate(sql_storage_queries_total{job=\"web-tools\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Goroutines Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"web-tools\"})"
    }
   ]
  },
  {
   "title": "GC Duration (75th percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000*sum(go_gc_duration_seconds{job=\"web-tools\",quantile=\"0.75\"})"
    }
   ]
  },
  {
   "title": "Heap Allocated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=\"web-tools\"})"
    }
   ]
  },
  {
   "title": "Heap Objects Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_objects{job=\"web-tools\"})"
    }
   ]
  }
 ]
}